image_width = 1024
image_height = 768

real = "-0.75"
imag = "0.0"
zoom = "1E0"

rotate = 0
approximation_order = 16
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = false
auto_adjust_iterations = true
remove_centre = false
export = "gui"

glitch_tolerance = 1.4e-6

probe_sampling = 15

data_storage_interval = 100

valid_iteration_probe_multiplier = 0.01

experimental = true  

coloring_type = "smooth_iteration"

jitter = false
jitter_factor = 0.2
show_output = true
iterations = 1000

palette_iteration_span = 100.0
palette_offset = 0
palette_cyclic = true

stripe_scale = 1.0
distance_transition = 10.0

lighting = true

lighting_direction = 30.0
lighting_azimuth = 35.0
lighting_opacity = 0.75
lighting_ambient = 0.4
lighting_diffuse = 0.5
lighting_specular = 0.5
lighting_shininess = 20