image_width = 1024
image_height = 768

real = "-0.75"
imag = "0.0"
zoom = "1E0"

rotate = 0
approximation_order = 16
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = false
auto_adjust_iterations = true
remove_centre = false
export = "gui"

glitch_tolerance = 1.4e-6

probe_sampling = 15

data_storage_interval = 100

valid_iteration_probe_multiplier = 0.01

experimental = true  
analytic_derivative = false

jitter = false
jitter_factor = 0.2
show_output = true
iterations = 1000

iteration_division = 100.0
palette_offset = 0